/**
 * Yinyan T&R Kernel — shared Hypothesis types.
 *
 * A Hypothesis is one candidate proposal for a task, generated by ONE
 * reasoning engine + persona/system-prompt flavor. The kernel asks N engines
 * (or N flavors of the same engine) to propose, then a deterministic selector
 * picks the winner — generation and selection are different components (A1).
 *
 * Source of truth for the multi-hypothesis path:
 *   - docs/design/extensible-thinking-system-design.md §4.1 (`multi-hypothesis` mode)
 *   - this file (kernel-internal types — NOT part of the IPC schema)
 *
 * Axiom anchors:
 *   - A1: branches dispatched to distinct engines/personas; the selector is rule-based.
 *   - A2: when no branch is acceptable, the kernel returns `type: 'unknown'`.
 *   - A3: selection is deterministic — no LLM scores or picks the winner.
 *   - A5: deterministic eliminators run BEFORE heuristic / probabilistic ranking.
 *   - A8: every hypothesis carries provenance (engineId, approachLabel, tokens).
 */
import type { REResponse, ReasoningEngine } from '../types.ts';

declare const HypothesisIdBrand: unique symbol;

/** Branded id so kernel-emitted hypotheses don't collide with bare strings. */
export type HypothesisId = string & { readonly [HypothesisIdBrand]: never };

export function hypothesisId(value: string): HypothesisId {
  return value as HypothesisId;
}

/**
 * Approach labels — the 1-word "flavor" the generator was asked to take.
 *
 * Values are bounded so the diversity fingerprint can compare across runs.
 * Adding a new label is a deliberate change: the selector's tiebreakers
 * already key off this set, and `parameter-registry`-tunable approach
 * weights (T5 calibrator) will be indexed by this enum.
 */
export type ApproachLabel = 'direct' | 'defensive' | 'minimal' | 'refactor-first' | 'exploratory';

export const APPROACH_LABELS: readonly ApproachLabel[] = [
  'direct',
  'defensive',
  'minimal',
  'refactor-first',
  'exploratory',
] as const;

/** A single proposal returned by one (engine, approach) branch. */
export interface Hypothesis {
  id: HypothesisId;
  /** Which RE produced this branch. Required for A1 oracle independence. */
  engineId: string;
  /** What flavor / system-prompt slant the generator was asked to take. */
  approachLabel: ApproachLabel;
  /** The proposal payload — opaque to the kernel; the verification layer interprets it. */
  content: string;
  /** Provider self-declared confidence if any; ignored by the selector when oracle scores exist (A5). */
  selfDeclaredConfidence?: number;
  /**
   * Diversity fingerprint — short stable hash of (approachLabel + content shape).
   * The kernel rejects branches whose fingerprint duplicates an earlier branch
   * past the diversity threshold so the multi-hypothesis path doesn't collapse
   * into N copies of the same answer (mode collapse).
   */
  diversityFingerprint: string;
  /** Token accounting for the budget guard. */
  tokensUsed: {
    input: number;
    output: number;
    thinking?: number;
  };
  /** Termination signal from the underlying engine — `limit_reached` taints confidence. */
  terminationReason: REResponse['terminationReason'];
  /**
   * T6 (Yinyan goal-grounding / A10): wall-clock timestamp at which this
   * hypothesis was generated. Snapshot of `Date.now()` taken inside the
   * generator. Pairs with `factHashes` to bind this proposal to a specific
   * world-graph state so downstream re-grounding can detect when the
   * underlying facts have changed since the hypothesis was synthesized.
   *
   * Optional + additive — older callers that construct Hypothesis literals
   * (test fixtures, custom adapters) keep working; the kernel and bridge
   * tolerate `undefined` and skip A10 staleness checks for that branch.
   */
  groundedAt?: number;
  /**
   * T6 (Yinyan goal-grounding / A10): list of `(factId, fileHash)` pairs
   * captured from the world-graph reads that informed this branch's
   * generation. When `WorldGraph.invalidateByFileHash` reports any of
   * these `fileHash` values mismatched against the current file content,
   * the hypothesis is flagged stale and the orchestrator re-grounds
   * (re-perceive + regenerate) rather than committing the proposal.
   *
   * Empty array means "no facts were consulted" (e.g. a pure conversational
   * task). Absent (undefined) means "this hypothesis predates the T6
   * binding" — staleness check is skipped.
   */
  factHashes?: ReadonlyArray<{ factId: string; fileHash: string }>;
}

/**
 * One branch directive given to the generator. The kernel constructs N of these
 * (one per intended branch) and dispatches them across distinct engines.
 */
export interface BranchSpec {
  approachLabel: ApproachLabel;
  /** Engine selected for this branch — picked by the kernel, never by an LLM. */
  engine: ReasoningEngine;
  /** System-prompt suffix that biases the engine toward `approachLabel`. */
  systemPromptOverlay: string;
}

/** Constraints the kernel enforces while generating branches. */
export interface MultiHypothesisPolicy {
  branches: 2 | 3 | 4;
  /**
   * Two diversity strategies map onto the existing `ThinkingConfig`
   * `multi-hypothesis.diversityConstraint` enum so the compiler→kernel
   * boundary stays one-way.
   *
   *   - 'different-patterns': vary `approachLabel` per branch (single-engine OK).
   *   - 'different-resources': REQUIRE distinct `engineId` per branch (A1 strong).
   */
  diversityConstraint: 'different-patterns' | 'different-resources';
  /**
   * Maximum allowed Jaccard overlap on the content shingle set before a
   * branch is considered a duplicate of an earlier one. Higher = stricter
   * rejection. Default 0.85 keeps near-identical answers out without
   * over-rejecting honest convergence.
   */
  maxFingerprintOverlap?: number;
}

/** Reason a branch was discarded — recorded for the kernel audit trail. */
export type BranchRejection =
  | { reason: 'duplicate'; collidedWith: HypothesisId; overlap: number }
  | { reason: 'engine-error'; message: string }
  | { reason: 'empty-content' }
  | { reason: 'budget-exhausted' };

/** Outcome of the L1 generation phase — passed to the selector verbatim. */
export interface GenerationOutcome {
  hypotheses: Hypothesis[];
  rejected: Array<{ approachLabel: ApproachLabel; engineId: string; rejection: BranchRejection }>;
  /** Aggregate token usage across attempted branches — the budget guard reads this. */
  totalTokens: { input: number; output: number; thinking: number };
}

/** Input shape for `HypothesisGenerator.generate`. */
export interface GenerationInput {
  /** Plain task instructions — same form passed to a single-shot generate. */
  systemPrompt: string;
  userPrompt: string;
  /** Per-branch token cap. Each branch's own `maxTokens` will be `≤ perBranchTokens`. */
  perBranchTokens: number;
  /** Aggregate ceiling — when crossed mid-generation the kernel stops spawning branches. */
  totalTokenCeiling?: number;
  /** Per-branch wall-clock cap (forwarded to `RERequest.timeoutMs`). */
  perBranchTimeoutMs?: number;
  /** Optional providerOptions forwarded verbatim (e.g. thinkingConfig per branch). */
  providerOptions?: Record<string, unknown>;
  /**
   * T6 (Yinyan goal-grounding / A10): pre-computed `(factId, fileHash)`
   * snapshot of the world-graph reads that informed the prompts above.
   * Each generated `Hypothesis.factHashes` will be populated with this
   * verbatim so the orchestrator can later detect when the underlying
   * facts have changed and re-ground.
   *
   * Optional + additive: callers that don't wire a fact-snapshot hook
   * leave it undefined. The generator falls back to an empty array on
   * each Hypothesis, signalling "T6 binding requested but no facts
   * recorded" — distinct from "T6 not wired" (legacy literal callers).
   */
  factHashes?: ReadonlyArray<{ factId: string; fileHash: string }>;
}
